"""change name column to username

Revision ID: 669e35ab5e0c
Revises: a73199844bfd
Create Date: 2021-11-21 10:20:07.756947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669e35ab5e0c'
down_revision = 'a73199844bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=False))
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
