"""empty message

Revision ID: 701d86d2aaa8
Revises: 644f8117cbae
Create Date: 2022-01-07 08:37:30.503477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701d86d2aaa8'
down_revision = '644f8117cbae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.String(length=80), nullable=False))
    op.drop_constraint('accounts_name_key', 'accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('accounts_name_key', 'accounts', ['name'])
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
