"""Revome test column from users table

Revision ID: 94abb4a74d00
Revises: 49c0fea66442
Create Date: 2021-11-19 13:22:13.992584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94abb4a74d00'
down_revision = '49c0fea66442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('test', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
