"""add accounts table

Revision ID: b92c106ea433
Revises: 538eb4402420
Create Date: 2022-06-09 15:45:35.121029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b92c106ea433'
down_revision = '538eb4402420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('account_number', sa.String(length=128), nullable=False),
    sa.Column('strategy', sa.String(length=128), nullable=True),
    sa.Column('custodian', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
